# Generated by Django 5.1.1 on 2025-01-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact',
            new_name='content',
        ),
    ]
